'use client'
import { useEffect, useState } from 'react'
import AppShell from '@/components/app-shell'
import { ensureWorkspace } from '@/lib/supabase/workspace'

type Customer={id:string;company_name:string;industry:string|null;company_size:string|null;country:string|null;website:string|null;contact_name:string|null;contact_email:string|null;status:string}
const blank={company_name:'',industry:'',company_size:'',country:'',website:'',contact_name:'',contact_email:'',status:'active'}
export default function CustomersPage(){const[items,setItems]=useState<Customer[]>([]);const[form,setForm]=useState(blank);const[show,setShow]=useState(false);const[q,setQ]=useState('');const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState('');const[orgId,setOrgId]=useState('')
 useEffect(()=>{let active=true;(async()=>{try{const{supabase,orgId}=await ensureWorkspace();if(!active)return;setOrgId(orgId);const{data,error}=await supabase.from('customers').select('id,company_name,industry,company_size,country,website,contact_name,contact_email,status').eq('org_id',orgId).order('company_name');if(error)throw error;if(active)setItems(data??[])}catch(e){if(active)setError(e instanceof Error?e.message:'Could not load customers.')}finally{if(active)setLoading(false)}})();return()=>{active=false}},[])
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');try{const{supabase}=await ensureWorkspace();const{data,error}=await supabase.from('customers').insert({...form,org_id:orgId}).select('id,company_name,industry,company_size,country,website,contact_name,contact_email,status').single();if(error)throw error;if(data)setItems(x=>[...x,data].sort((a,b)=>a.company_name.localeCompare(b.company_name)));setForm(blank);setShow(false)}catch(e){setError(e instanceof Error?e.message:'Could not create customer.')}finally{setSaving(false)}}
 const filtered=items.filter(x=>[x.company_name,x.industry,x.company_size,x.country,x.contact_name,x.contact_email,x.website].filter(Boolean).join(' ').toLowerCase().includes(q.toLowerCase()))
 return <AppShell title="Customers" subtitle="Keep your account and prospect base separate from the public channel directory, ready for opportunity routing."><div className="mb-5 flex flex-col gap-3 sm:flex-row"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search customers" className="flex-1 rounded-xl border border-slate-800 bg-slate-900 px-4 py-3 text-sm outline-none focus:border-blue-500"/><button onClick={()=>setShow(v=>!v)} className="rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold hover:bg-blue-500">{show?'Close':'Add customer'}</button></div>{error&&<div className="mb-5 rounded-xl border border-red-900 bg-red-950/20 p-4 text-sm text-red-300">{error}</div>}{show&&<form onSubmit={save} className="mb-5 rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3"><Input label="Company name" value={form.company_name} onChange={v=>setForm({...form,company_name:v})} required/><Input label="Industry" value={form.industry} onChange={v=>setForm({...form,industry:v})}/><Input label="Company size" value={form.company_size} onChange={v=>setForm({...form,company_size:v})}/><Input label="Country" value={form.country} onChange={v=>setForm({...form,country:v})}/><Input label="Website" value={form.website} onChange={v=>setForm({...form,website:v})}/><Input label="Contact name" value={form.contact_name} onChange={v=>setForm({...form,contact_name:v})}/><Input label="Contact email" value={form.contact_email} onChange={v=>setForm({...form,contact_email:v})}/></div><button disabled={saving} className="mt-5 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold disabled:opacity-50">{saving?'Saving…':'Create customer'}</button></form>}{loading?<div className="rounded-xl border border-slate-800 bg-slate-900 p-8 text-center text-slate-500">Loading customers…</div>:filtered.length===0?<div className="rounded-xl border border-dashed border-slate-800 p-10 text-center text-slate-500">No customers yet. Add a customer to start building your opportunity pipeline.</div>:<div className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900"><div className="hidden grid-cols-[1.6fr_1fr_1fr_1fr] gap-4 border-b border-slate-800 px-5 py-3 text-xs uppercase tracking-wider text-slate-600 sm:grid"><span>Company</span><span>Industry</span><span>Size</span><span>Country</span></div>{filtered.map(c=><div key={c.id} className="grid gap-2 border-b border-slate-800 px-5 py-4 last:border-0 sm:grid-cols-[1.6fr_1fr_1fr_1fr] sm:gap-4"><div><p className="font-medium text-slate-200">{c.company_name}</p><p className="mt-1 text-xs text-slate-500">{c.contact_name||c.contact_email||'No contact added'}</p></div><span className="text-sm text-slate-400">{c.industry||'—'}</span><span className="text-sm text-slate-400">{c.company_size||'—'}</span><span className="text-sm text-slate-400">{c.country||'—'}</span></div>)}</div>}</AppShell>}
function Input({label,value,onChange,required}:{label:string;value:string;onChange:(v:string)=>void;required?:boolean}){return <label className="text-sm text-slate-300">{label}<input required={required} value={value} onChange={e=>onChange(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm outline-none focus:border-blue-500"/></label>}
