'use client'

import { FormEvent, useEffect, useState, type ReactNode } from 'react'
import { useRouter } from 'next/navigation'
import AppShell from '@/components/app-shell'
import { getAuthenticatedClient } from '@/lib/supabase/client'

type Option={id:string;name:string}
const input='mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-900 placeholder-slate-600 outline-none focus:border-blue-500'

export default function NewProductPage(){
 const router=useRouter(); const [vendors,setVendors]=useState<Option[]>([]); const [categories,setCategories]=useState<Option[]>([]); const [loadingOptions,setLoadingOptions]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState('')
 const [form,setForm]=useState({name:'',vendor_id:'',category_id:'',description:'',capabilities:'',target_company_size:'',industries:'',deployment_type:'',pricing_model:''})
 useEffect(()=>{let active=true; void getAuthenticatedClient().then(({supabase,error:authError})=>{if(authError)throw authError;return Promise.all([supabase.from('vendors').select('id,name').eq('is_active',true).order('name'),supabase.from('technology_categories').select('id,name').order('name')])}).then(([vr,cr])=>{if(!active)return;if(vr.error||cr.error)throw vr.error||cr.error;setVendors(vr.data||[]);setCategories(cr.data||[]);setLoadingOptions(false)}).catch(()=>{if(active){setError('Could not load product options.');setLoadingOptions(false)}});return()=>{active=false}},[])
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');if(!form.category_id){setError('Select a technology category.');return}setSaving(true);try{const {supabase,error:authError}=await getAuthenticatedClient();if(authError)throw authError;const category=categories.find(x=>x.id===form.category_id);const {error}=await supabase.from('products').insert({name:form.name.trim(),slug:form.name.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),vendor_id:form.vendor_id||null,category_id:form.category_id,category_name:category?.name||null,description:form.description.trim()||null,core_capabilities:form.capabilities.split(',').map(v=>v.trim()).filter(Boolean),target_company_size:form.target_company_size.split(',').map(v=>v.trim()).filter(Boolean),industries:form.industries.split(',').map(v=>v.trim()).filter(Boolean),deployment_type:form.deployment_type.split(',').map(v=>v.trim()).filter(Boolean),pricing_model:form.pricing_model.trim()||null,source_type:'manual',is_active:true});if(error)throw error;router.replace('/products');router.refresh()}catch(cause){setError(cause instanceof Error?cause.message:'Could not create product.')}finally{setSaving(false)}}
 return <AppShell title="Add product" subtitle="Add a real product to the shared catalog with structured data for matching and commercial workflows."><form onSubmit={submit} className="max-w-3xl rounded-2xl border border-slate-200 bg-slate-50 p-6"><div className="grid gap-5 md:grid-cols-2"><Field label="Product name *"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className={input}/></Field><Field label="Vendor"><select value={form.vendor_id} onChange={e=>setForm({...form,vendor_id:e.target.value})} className={input}><option value="">No vendor assigned</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></Field><Field label="Technology category *"><select required disabled={loadingOptions} value={form.category_id} onChange={e=>setForm({...form,category_id:e.target.value})} className={input}><option value="">Select category</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Pricing model"><input value={form.pricing_model} onChange={e=>setForm({...form,pricing_model:e.target.value})} placeholder="Subscription, per-user, perpetual…" className={input}/></Field><Field label="Core capabilities"><input value={form.capabilities} onChange={e=>setForm({...form,capabilities:e.target.value})} placeholder="Backup, EDR, analytics" className={input}/></Field><Field label="Target company size"><input value={form.target_company_size} onChange={e=>setForm({...form,target_company_size:e.target.value})} placeholder="SMB, Mid-market, Enterprise" className={input}/></Field><Field label="Industries"><input value={form.industries} onChange={e=>setForm({...form,industries:e.target.value})} placeholder="Healthcare, Finance, Technology" className={input}/></Field><Field label="Deployment type"><input value={form.deployment_type} onChange={e=>setForm({...form,deployment_type:e.target.value})} placeholder="SaaS, on-prem, hybrid" className={input}/></Field><label className="text-sm text-slate-700 md:col-span-2">Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} rows={4} className={input}/></label></div>{error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}<div className="mt-5 flex gap-3"><button disabled={saving} className="rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-semibold disabled:opacity-50">{saving?'Saving…':'Add product'}</button><button type="button" onClick={()=>router.back()} className="rounded-xl border border-slate-200 px-5 py-2.5 text-sm text-slate-700">Cancel</button></div></form></AppShell>
}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="text-sm text-slate-700">{label}{children}</label>}
