'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import AppShell from '@/components/app-shell'
import { ensureWorkspace } from '@/lib/supabase/workspace'

type Distributor = { id: string; name: string; website: string | null; country: string | null; regions: string[] | null; specializations: string[] | null; services: string[] | null; sales_regions: string[] | null; is_active: boolean }

export default function DistributorsPage() {
  const [items,setItems]=useState<Distributor[]>([]); const [q,setQ]=useState(''); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [workspaceDistributorId,setWorkspaceDistributorId]=useState<string|null>(null); const [connecting,setConnecting]=useState<string|null>(null)
  useEffect(()=>{let active=true;(async()=>{try{const {supabase,orgId}=await ensureWorkspace();const [distributorResult,workspaceResult]=await Promise.all([supabase.from('distributors').select('id,name,website,country,regions,specializations,services,sales_regions,is_active').eq('is_active',true).order('name'),supabase.from('org_distributors').select('distributor_id').eq('org_id',orgId).maybeSingle()]);if(distributorResult.error)throw distributorResult.error;if(workspaceResult.error)throw workspaceResult.error;if(!active)return;setItems(distributorResult.data??[]);setWorkspaceDistributorId(workspaceResult.data?.distributor_id??null)}catch(cause){if(active)setError(cause instanceof Error?cause.message:'Could not load distributors.')}finally{if(active)setLoading(false)}})();return()=>{active=false}},[])
  const filtered=useMemo(()=>{const n=q.trim().toLowerCase();return n?items.filter(x=>[x.name,x.country,x.website,(x.regions??[]).join(' '),(x.specializations??[]).join(' '),(x.services??[]).join(' '),(x.sales_regions??[]).join(' ')].filter(Boolean).join(' ').toLowerCase().includes(n)):items},[items,q])
  async function useAsWorkspaceDistributor(distributorId:string){setConnecting(distributorId);setError('');try{const {supabase,orgId,user}=await ensureWorkspace();const {error:upsertError}=await supabase.from('org_distributors').upsert({org_id:orgId,distributor_id:distributorId,owner_id:user.id,status:'active'},{onConflict:'org_id'});if(upsertError)throw upsertError;setWorkspaceDistributorId(distributorId)}catch(cause){setError(cause instanceof Error?cause.message:'Could not set workspace distributor.')}finally{setConnecting(null)}}
  return <AppShell title="Distributor network" subtitle="Explore distribution organizations that can connect vendors with regional partner ecosystems."><div className="mb-5 flex flex-col gap-3 sm:flex-row"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search distributors, regions or specializations" className="flex-1 rounded-xl border border-slate-800 bg-slate-900 px-4 py-3 text-sm outline-none focus:border-blue-500" /><Link href="/distributors/new" className="rounded-xl border border-slate-700 px-4 py-3 text-center text-sm font-semibold text-slate-200 hover:border-blue-500">Add distributor</Link></div>{error&&<div className="mb-5 rounded-xl border border-red-900 bg-red-950/20 p-4 text-sm text-red-300">{error}</div>}{loading?<div className="rounded-xl border border-slate-800 bg-slate-900 p-8 text-center text-slate-500">Loading distributors…</div>:filtered.length===0?<div className="rounded-xl border border-dashed border-slate-800 p-10 text-center text-slate-500">No distributors match this search.</div>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(d=><article key={d.id} className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">{d.name}</h2>{workspaceDistributorId===d.id&&<span className="mt-2 inline-flex rounded-full border border-emerald-900 px-2 py-1 text-[11px] text-emerald-400">Workspace distributor</span>}</div>{d.country&&<span className="rounded-full border border-slate-700 px-2 py-1 text-[11px] text-slate-400">{d.country}</span>}</div><p className="mt-4 text-sm leading-6 text-slate-400">{(d.specializations??[]).slice(0,5).join(' · ')||'Distribution capabilities available in the directory.'}</p><div className="mt-4 flex flex-wrap gap-2">{(d.regions??d.sales_regions??[]).slice(0,4).map(r=><span key={r} className="rounded-full bg-slate-950 px-2.5 py-1 text-xs text-slate-500">{r}</span>)}</div>{d.website&&<a href={d.website} target="_blank" rel="noreferrer" className="mt-5 inline-block text-xs text-blue-400 hover:text-blue-300">Visit website →</a>}<button onClick={()=>void useAsWorkspaceDistributor(d.id)} disabled={connecting===d.id||workspaceDistributorId===d.id} className="mt-4 w-full rounded-lg border border-slate-700 px-3 py-2 text-sm font-semibold text-slate-300 hover:border-blue-500 disabled:opacity-50">{connecting===d.id?'Connecting…':workspaceDistributorId===d.id?'Selected for workspace':'Use as workspace distributor'}</button></article>)}</div>}</AppShell>
}
