'use client'

import { useEffect, useMemo, useState } from 'react'
import AppShell from '@/components/app-shell'
import { createClient } from '@/lib/supabase/client'

type Distributor = { id: string; name: string; website: string | null; country: string | null; regions: string[] | null; specializations: string[] | null; services: string[] | null; sales_regions: string[] | null; is_active: boolean }

export default function DistributorsPage() {
  const [items,setItems]=useState<Distributor[]>([]); const [q,setQ]=useState(''); const [loading,setLoading]=useState(true); const [error,setError]=useState('')
  useEffect(()=>{const supabase=createClient();supabase.from('distributors').select('id,name,website,country,regions,specializations,services,sales_regions,is_active').eq('is_active',true).order('name').then(({data,error})=>{if(error)setError('Could not load distributors.');else setItems(data??[]);setLoading(false)})},[])
  const filtered=useMemo(()=>{const n=q.trim().toLowerCase();return n?items.filter(x=>[x.name,x.country,x.website,(x.regions??[]).join(' '),(x.specializations??[]).join(' '),(x.services??[]).join(' '),(x.sales_regions??[]).join(' ')].filter(Boolean).join(' ').toLowerCase().includes(n)):items},[items,q])
  return <AppShell title="Distributor network" subtitle="Explore distribution organizations that can connect vendors with regional partner ecosystems."><div className="mb-5"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search distributors, regions or specializations" className="w-full rounded-xl border border-slate-800 bg-slate-900 px-4 py-3 text-sm outline-none focus:border-blue-500" /></div>{error&&<div className="mb-5 rounded-xl border border-red-900 bg-red-950/20 p-4 text-sm text-red-300">{error}</div>}{loading?<div className="rounded-xl border border-slate-800 bg-slate-900 p-8 text-center text-slate-500">Loading distributors…</div>:filtered.length===0?<div className="rounded-xl border border-dashed border-slate-800 p-10 text-center text-slate-500">No distributors match this search.</div>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(d=><article key={d.id} className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex items-start justify-between gap-3"><h2 className="font-semibold">{d.name}</h2>{d.country&&<span className="rounded-full border border-slate-700 px-2 py-1 text-[11px] text-slate-400">{d.country}</span>}</div><p className="mt-4 text-sm leading-6 text-slate-400">{(d.specializations??[]).slice(0,5).join(' · ')||'Distribution capabilities available in the directory.'}</p><div className="mt-4 flex flex-wrap gap-2">{(d.regions??d.sales_regions??[]).slice(0,4).map(r=><span key={r} className="rounded-full bg-slate-950 px-2.5 py-1 text-xs text-slate-500">{r}</span>)}</div>{d.website&&<a href={d.website} target="_blank" rel="noreferrer" className="mt-5 inline-block text-xs text-blue-400 hover:text-blue-300">Visit website →</a>}</article>)}</div>}</AppShell>
}
