'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import AppShell from '@/components/app-shell'
import { createClient } from '@/lib/supabase/client'

type Vendor = { id: string; name: string; website: string | null; categories: string[] | null; target_customers: string | null; geographic_coverage: string[] | null; market_segment: string | null; is_active: boolean }

export default function VendorsPage() {
  const [items, setItems] = useState<Vendor[]>([]); const [q, setQ] = useState(''); const [loading,setLoading]=useState(true); const [error,setError]=useState('')
  useEffect(()=>{ const supabase=createClient(); supabase.from('vendors').select('id,name,website,categories,target_customers,geographic_coverage,market_segment,is_active').eq('is_active',true).order('name').then(({data,error})=>{ if(error) setError('Could not load vendors.'); else setItems(data??[]); setLoading(false) }) },[])
  const filtered=useMemo(()=>{const n=q.trim().toLowerCase(); return n?items.filter(x=>[x.name,x.website,x.target_customers,x.market_segment,(x.categories??[]).join(' '),(x.geographic_coverage??[]).join(' ')].filter(Boolean).join(' ').toLowerCase().includes(n)):items},[items,q])
  return <AppShell title="Vendor ecosystem" subtitle="Browse the vendor layer and use it as the source for future channel matching."><div className="mb-5 flex flex-col gap-3 sm:flex-row"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search vendors, categories or markets" className="flex-1 rounded-xl border border-slate-800 bg-slate-900 px-4 py-3 text-sm outline-none focus:border-blue-500" /><Link href="/vendors/new" className="rounded-xl border border-slate-700 px-4 py-3 text-center text-sm font-semibold text-slate-200 hover:border-blue-500">Add vendor</Link><Link href="/discovery" className="rounded-xl bg-blue-600 px-4 py-3 text-center text-sm font-semibold hover:bg-blue-500">Find partners for a vendor</Link></div>{error&&<div className="rounded-xl border border-red-900 bg-red-950/20 p-4 text-sm text-red-300">{error}</div>}{loading?<div className="rounded-xl border border-slate-800 bg-slate-900 p-8 text-center text-slate-500">Loading vendors…</div>:filtered.length===0?<div className="rounded-xl border border-dashed border-slate-800 p-10 text-center text-slate-500">No vendors match this search.</div>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map(v=><article key={v.id} className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex items-start justify-between gap-3"><h2 className="font-semibold">{v.name}</h2>{v.market_segment&&<span className="rounded-full border border-slate-700 px-2 py-1 text-[11px] text-slate-400">{v.market_segment}</span>}</div><p className="mt-3 min-h-12 text-sm leading-6 text-slate-400">{v.target_customers||'Vendor profile available in the intelligence layer.'}</p><div className="mt-4 flex flex-wrap gap-2">{(v.categories??[]).slice(0,4).map(c=><span key={c} className="rounded-full bg-slate-950 px-2.5 py-1 text-xs text-slate-500">{c}</span>)}</div>{v.website&&<a href={v.website} target="_blank" rel="noreferrer" className="mt-5 inline-block text-xs text-blue-400 hover:text-blue-300">Visit website →</a>}</article>)}</div>}</AppShell>
}
